### ISSUE TITLE
Rotation removes one more log than it should?

### ISSUE THREAD

**Issue by antonjonsson** [dstokes/log-rotate#5]
Good chance I am missing something since this seems so basic, but still felt I needed to ask.

Lets say I am rotating my test.log. First time I call the rotate function it simply renames test.log to test.log.0:

`rotate('./test.log', { count: 2 }, function(err) {`
`// ls ./ => test.log.0`
`});`

More stuff gets written to test.log, and I call rotate again:

`rotate('./test.log', { count: 2 }, function(err) {`
`// ls ./ => test.log.0, test.log.1`
`});`

Now, if more is written to test.log I will be in a state where I have 3 logs (test.log, test.log.0, test.log.1). But if I call rotate from this state:

`rotate('./test.log', { count: 2 }, function(err) {`
`// ls ./ => test.log.0`
`});`

What I expect to have happen is test.log.0 to be moved to test.log.1, and test.log to be moved to test.log.0, but instead it only keeps one of them.

**Comment by FASTLIKETREE** [comment]
The count includes the log you are currently writing.
