### ISSUE TITLE
log-rotate not honoring log limit (occasionally loglimit + 1)

### ISSUE THREAD

**Issue by FASTLIKETREE** [dstokes/log-rotate#6]
Running log in a tight loop occasionally leads to (loglimit+1) number of logs. 
I can reproduce 100% of the time with 10000 log messages, but not with 20000, 50000, or 100000. 

Line 66 in index.js looks to be the start of the issue.
 66       if (count !== null && toShift.length > count && i <= (toShift.length - count)) {
 67         return remove(target);
 68       }

If toShift.length is equal to your log limit, then no files will be removed, the rotate code continues renaming all your logs up to your loglimit log which gets renamed (logname).(loglimit + 1). If the rotate code is not called again, you are stuck with your extra log (logname).(loglimit+1).

If toShift.length is 1 greater than count things work as expected, 2 log files are removed (logname).(loglimit) and (logname).(loglimit + 1), the logs are then rotated so that (logname).(loglimit - 1) becomes (logname).(loglimit) and (logname) becomes (logname).0 making room for the new write stream to create a new file (logname). Instead the condition comparing against the count should be changed to >= so that a single log file is removed when toShift is equal to your count.

Changing line 66 to 
 66       if (count !== null && toShift.length >= count && i <= (toShift.length - count)) {
solves my issue.

Another approach might be to do the deletes after the rotate completes successfully.

**Comment by antonjonsson** [comment]
This is actually the exact issue we are having too. Guess I was not very clear in my description in #5

**Comment by dstokes** [comment]
Thanks @FASTLIKETREE and @antonjonsson for reporting this. My tests were incorrect and concealed this bug. Your recommendation was spot! 👏
